import {
  Activity,
  Bell,
  BookOpen,
  Brain,
  Coffee,
  Cpu,
  Eye,
  FileCheck,
  FileText,
  Fingerprint,
  GitBranch,
  Heart,
  Image,
  Layers,
  Lightbulb,
  Lock,
  Map,
  MessageSquare,
  Mic,
  Palette,
  Scale,
  Search,
  Shield,
  ShoppingBag,
  Sparkles,
  Star,
  Users,
  Zap,
} from 'lucide-react';
import type {
  SkillCategory,
  SkillConsentType,
  SkillDefinition,
  SkillEntryPoint,
  SkillOperationalStatus,
  SkillOutputType,
  SkillSafetyLevel,
  SkillStatus,
  SkillSurface,
} from './types';

export type SkillMeta = SkillDefinition;

type SkillInput = {
  id: string;
  skillId?: string;
  canonicalCodexSkill?: string;
  aliases?: string[];
  title: string;
  shortTitle?: string;
  subtitle: string;
  icon: SkillDefinition['icon'];
  color: string;
  status: SkillStatus;
  operationalStatus?: SkillOperationalStatus;
  category: SkillCategory;
  description: string;
  keyFeatures: string[];
  primarySurface: SkillSurface;
  entryPoints: SkillEntryPoint[];
  requiredConsent?: SkillConsentType[];
  privacyNotes?: string[];
  safetyLevel?: SkillSafetyLevel;
  aiFeatureKey?: string;
  serverRoute?: string;
  outputType?: SkillOutputType;
  prerequisites?: string[];
  dataInputs?: string[];
  dataExclusions?: string[];
  userActions?: string[];
  adminActions?: string[];
  testsRequired?: string[];
  recommendedNextActions?: string[];
  demoModeBehavior?: string;
  featured?: boolean;
};

const entry = (
  surface: SkillSurface,
  label: string,
  description: string,
  route?: string,
  featured = false,
): SkillEntryPoint => ({ surface, label, description, route, featured });

const DEFAULT_PRIVACY_NOTES = [
  'Uses the minimum context needed for the surface.',
  'Does not expose private taste internals, hidden ranking weights, or other members raw answers.',
  'AI output is assistive only; the member stays in control.',
];

const AI_FEATURE_ROUTES: Record<string, string> = {
  bio_coach: '/api/ai/coach-bio',
  profile_completeness: '/api/ai/profile-completeness',
  taste_profile: '/api/ai/taste-profile',
  why_match: '/api/ai/explain-match',
  safety_scan: '/api/ai/message-safety',
  date_planner: '/api/ai/plan-date',
  safety_advice: '/api/ai/safety-advice',
  rephrase_message: '/api/ai/rephrase',
  generate_openers: '/api/ai/openers',
  personality_profile: '/api/ai/personality-profile',
  compatibility_reflection: '/api/ai/compatibility-reflection',
  pacing_coach: '/api/ai/pacing-intervention',
  mod_summarizer: '/api/ai/moderation-summary',
  visual_icebreaker: '/api/ai/analyze-photos',
};

const defaultOperationalStatus = (input: SkillInput): SkillOperationalStatus => {
  if (input.operationalStatus) return input.operationalStatus;
  if (input.status === 'gated') return 'gated_dependency';
  if (input.safetyLevel === 'internal' || input.outputType === 'reference') return 'partially_operational';
  return 'operational';
};

const defineSkill = (input: SkillInput): SkillDefinition => {
  const surfaces = new Set<SkillSurface>(['skills-hub', 'skills', input.primarySurface]);
  input.entryPoints.forEach((point) => surfaces.add(point.surface));
  const canonicalCodexSkill = input.canonicalCodexSkill ?? input.skillId ?? input.id;
  const recommendedActions = input.recommendedNextActions ?? input.entryPoints.map((point) => point.label);

  return {
    id: input.id,
    slug: input.id,
    skillId: input.skillId,
    canonicalCodexSkill,
    aliases: Array.from(new Set([canonicalCodexSkill, input.id, input.shortTitle ?? input.title, ...(input.aliases ?? [])])),
    title: input.title,
    shortTitle: input.shortTitle ?? input.title,
    subtitle: input.subtitle,
    category: input.category,
    status: input.status,
    operationalStatus: defaultOperationalStatus(input),
    summary: input.description,
    fullDescription: `${input.description} ${input.keyFeatures.join(' ')}`,
    featured: input.featured ?? true,
    icon: input.icon,
    color: input.color,
    primarySurface: input.primarySurface,
    availableSurfaces: Array.from(surfaces),
    entryPoints: input.entryPoints,
    requiredConsent: input.requiredConsent ?? ['none'],
    privacyNotes: input.privacyNotes ?? DEFAULT_PRIVACY_NOTES,
    safetyLevel: input.safetyLevel ?? 'low',
    aiFeatureKey: input.aiFeatureKey,
    serverRoute: input.serverRoute ?? (input.aiFeatureKey ? AI_FEATURE_ROUTES[input.aiFeatureKey] : undefined),
    outputType: input.outputType ?? 'reference',
    prerequisites: input.prerequisites ?? ['Member is signed into the Kesher prototype.'],
    dataInputs: input.dataInputs ?? ['surface context', 'member-controlled settings'],
    dataExclusions: input.dataExclusions ?? [
      'raw personality answers',
      'hidden ranking weights',
      'protected-trait inference',
      'exact addresses',
      'private messages unless explicitly drafted by the member',
    ],
    userActions: input.userActions ?? recommendedActions,
    adminActions: input.adminActions ?? (input.safetyLevel === 'internal' ? ['Review in admin/ops only'] : []),
    testsRequired: input.testsRequired ?? ['registry_render', 'launcher_state_transition', 'privacy_guardrail'],
    recommendedNextActions: recommendedActions,
    demoModeBehavior: input.demoModeBehavior ?? 'Starts a demo-safe skill state and opens the related prototype surface when available.',
    description: input.description,
    keyFeatures: input.keyFeatures,
  };
};

export const SKILLS: SkillDefinition[] = [
  defineSkill({
    id: 'personality-assessment',
    skillId: 'kesher-bfas-assessment',
    title: 'Personality Assessment',
    shortTitle: 'Assessment',
    subtitle: 'Progressive BFAS/IPIP Administration',
    icon: Brain,
    color: 'bg-violet-100 text-violet-700 border-violet-200',
    status: 'prototype',
    category: 'personality',
    description: 'Progressive personality questionnaire with save-and-resume, domain and facet scoring, quality checks, and bilingual reflection card generation.',
    keyFeatures: ['100-item BFAS or IPIP-NEO public-domain paths', 'Reverse-keyed items with deterministic scoring', 'Response quality gates before scoring', 'Save-and-resume in blocks of 10 to 15 items'],
    primarySurface: 'onboarding',
    entryPoints: [
      entry('profile-builder', 'Start assessment', 'Open the private personality assessment from profile setup.', '/settings/personality', true),
      entry('settings', 'Manage assessment', 'Review or reset the personality journey.', '/settings/personality'),
    ],
    requiredConsent: ['profile_data'],
    aiFeatureKey: 'personality_profile',
    outputType: 'reflection',
  }),
  defineSkill({
    id: 'personality-profile',
    skillId: 'kesher-personality-profile',
    title: 'Personality Profile',
    shortTitle: 'Profile Cards',
    subtitle: 'Private Reflection Cards',
    icon: FileText,
    color: 'bg-teal-100 text-teal-700 border-teal-200',
    status: 'prototype',
    category: 'personality',
    description: 'Translates deterministic BFAS domain and aspect scores into warm private reflection cards via structured Gemini output. Owner-only by default.',
    keyFeatures: ['Domain and aspect cards in the member language', 'AI receives tendency bands only, not exact values', 'No clinical labels, fixed identities, or match claims', 'Export, reset, and delete controls remain visible'],
    primarySurface: 'settings',
    entryPoints: [
      entry('profile-builder', 'Review reflection cards', 'Save private reflection output during profile setup.', '/settings/personality', true),
      entry('settings', 'Open profile cards', 'Manage owner-only personality cards.', '/settings/personality'),
    ],
    requiredConsent: ['profile_data', 'ai_assist'],
    aiFeatureKey: 'personality_profile',
    outputType: 'reflection',
  }),
  defineSkill({
    id: 'personality-engine',
    skillId: 'kesher-personality-engine',
    title: 'Personality Engine',
    shortTitle: 'Engine',
    subtitle: 'BFAS Scoring & Reflection Pipeline',
    icon: Cpu,
    color: 'bg-violet-100 text-violet-700 border-violet-200',
    status: 'prototype',
    category: 'personality',
    description: 'BFAS assessment system covering test administration, deterministic scoring, private reports, pair reflections, and personality-aware explanation guardrails.',
    keyFeatures: ['Deterministic scoring with no LLM scoring', 'Structured output schemas for reflections', 'Versioned item bank with migration path', 'Bilingual Hebrew and English support with invariance checks'],
    primarySurface: 'profile-builder',
    entryPoints: [
      entry('profile-builder', 'Use scoring pipeline', 'Open the profile builder assessment flow.', '/settings/personality', true),
      entry('ai-trust', 'Inspect AI boundary', 'Review how personality outputs are governed.', '/settings/ai-trust'),
    ],
    requiredConsent: ['profile_data', 'ai_assist'],
    aiFeatureKey: 'personality_profile',
    outputType: 'reflection',
  }),
  defineSkill({
    id: 'personality-research',
    skillId: 'kesher-personality-research',
    title: 'Personality Research',
    shortTitle: 'Research',
    subtitle: 'Evidence & Claims Grounding',
    icon: BookOpen,
    color: 'bg-violet-100 text-violet-700 border-violet-200',
    status: 'prototype',
    category: 'personality',
    description: 'Evidence-tagged grounding for personality claims, compatibility language, and trust copy so contracts remain scientifically and ethically defensible.',
    keyFeatures: ['Claim-evidence traceability', 'Research citation discipline', 'Compatibility language safety rails', 'Grounding checks for trust copy'],
    primarySurface: 'profile-builder',
    entryPoints: [
      entry('profile-builder', 'Use evidence-grounded prompts', 'Apply research-safe language while building the profile.', '/profile/edit', true),
      entry('ai-trust', 'Review claim boundaries', 'Open AI transparency controls.', '/settings/ai-trust'),
    ],
    requiredConsent: ['none'],
    outputType: 'reference',
  }),
  defineSkill({
    id: 'personality-ocean',
    skillId: 'kesher-personality-ocean',
    title: 'Personality & OCEAN',
    shortTitle: 'OCEAN',
    subtitle: 'Jewish Observance Integration',
    icon: Star,
    color: 'bg-amber-100 text-amber-700 border-amber-200',
    status: 'prototype',
    category: 'personality',
    description: 'OCEAN model implementation integrated with Jewish observance layers and Hebrew-first localization for culturally aware reflection cards.',
    keyFeatures: ['OCEAN traits mapped to dating-relevant dimensions', 'Observance-layer signals overlay', 'Hebrew-first with RTL layout support', 'Cultural context in reflection cards'],
    primarySurface: 'profile-builder',
    entryPoints: [
      entry('profile-builder', 'Reflect on values', 'Use culturally aware reflection during profile building.', '/settings/personality', true),
      entry('daily', 'See values context', 'Review visible overlap in Daily Picks.', '/daily'),
    ],
    requiredConsent: ['profile_data'],
    aiFeatureKey: 'personality_profile',
    outputType: 'reflection',
  }),
  defineSkill({
    id: 'personality-visibility',
    skillId: 'kesher-personality-visibility',
    title: 'Personality Visibility',
    shortTitle: 'Visibility',
    subtitle: 'Four-Layer Visibility Model',
    icon: Eye,
    color: 'bg-orange-100 text-orange-700 border-orange-200',
    status: 'prototype',
    category: 'personality',
    description: 'Defines which personality-derived data can appear in public browse, private owner, mutual-consent, or system-only surfaces.',
    keyFeatures: ['Public, private, mutual-consent, and system-only layers', 'Per-surface field classification matrix', 'Discovery never shows model-derived trait labels', 'ADR required for any visibility policy change'],
    primarySurface: 'settings',
    entryPoints: [
      entry('settings', 'Open visibility settings', 'Control what personality context can be shared.', '/settings/personality-visibility', true),
      entry('ai-trust', 'Review data use', 'See the AI and privacy boundary.', '/settings/ai-trust'),
    ],
    requiredConsent: ['profile_data'],
    outputType: 'settings',
  }),
  defineSkill({
    id: 'consent-ux',
    skillId: 'kesher-consent-ux',
    title: 'Consent UX',
    shortTitle: 'Consent',
    subtitle: 'Trust Hub & Grants Ledger',
    icon: Shield,
    color: 'bg-emerald-100 text-emerald-700 border-emerald-200',
    status: 'prototype',
    category: 'privacy',
    description: 'Section 11 consent gates, Trust Hub dashboard, grants ledger, revocation flows, and anti-dark-pattern consent microcopy.',
    keyFeatures: ['Section 11 disclosure requirements', 'Pre-checked boxes forbidden and default off', 'Revocation in two taps from Trust Hub', 'Audit log of consent events'],
    primarySurface: 'ai-trust',
    entryPoints: [
      entry('ai-trust', 'Open consent controls', 'Manage grants and revocation from the AI Trust Hub.', '/settings/ai-trust', true),
      entry('onboarding', 'Review consent before AI', 'Show consent before optional coaching.', '/profile/edit'),
    ],
    requiredConsent: ['none'],
    outputType: 'settings',
  }),
  defineSkill({
    id: 'israeli-privacy',
    skillId: 'kesher-israeli-privacy',
    title: 'Israeli Privacy Compliance',
    shortTitle: 'Privacy Law',
    subtitle: 'Amendment 13 & PPA Guidance',
    icon: Lock,
    color: 'bg-blue-100 text-blue-700 border-blue-200',
    status: 'prototype',
    category: 'privacy',
    description: 'Data classification matrix, Section 11 notice, access, correction, deletion rights, DPO triggers, and transfer-abroad controls.',
    keyFeatures: ['Sensitive data classification', 'Statutory access, correction, and deletion rights', 'DPO trigger conditions', 'Transfer-abroad safeguards'],
    primarySurface: 'ai-trust',
    entryPoints: [
      entry('ai-trust', 'Review privacy controls', 'Open AI and privacy transparency.', '/settings/ai-trust', true),
      entry('safety', 'Open safety and rights', 'Keep privacy rights near safety actions.', '/settings/safety'),
    ],
    requiredConsent: ['none'],
    safetyLevel: 'medium',
    outputType: 'settings',
  }),
  defineSkill({
    id: 'privacy-recommendation',
    skillId: 'kesher-privacy-preserving-recommendation',
    title: 'Privacy-Preserving Recommendation',
    shortTitle: 'Private Ranking',
    subtitle: 'Three-Layer Architecture',
    icon: Layers,
    color: 'bg-indigo-100 text-indigo-700 border-indigo-200',
    status: 'prototype',
    category: 'privacy',
    description: 'Silent personalization, safe explanation, and permissioned personality layers with signal allowlists and anti-leakage controls.',
    keyFeatures: ['Three-layer signal architecture', 'Explanation layer uses only whitelisted reasons', 'Silent personalization never exposed to other users', 'Anti-leakage controls at every boundary'],
    primarySurface: 'daily',
    entryPoints: [
      entry('daily', 'Tune Daily Picks privately', 'Use private ranking without exposing taste internals.', '/daily', true),
      entry('ai-trust', 'Review recommendation privacy', 'Open AI data controls.', '/settings/ai-trust'),
    ],
    requiredConsent: ['private_taste'],
    aiFeatureKey: 'taste_profile',
    outputType: 'settings',
  }),
  defineSkill({
    id: 'private-taste',
    skillId: 'kesher-private-taste',
    title: 'Private Taste',
    shortTitle: 'Taste',
    subtitle: 'Owner-Only Preference Learning',
    icon: Fingerprint,
    color: 'bg-purple-100 text-purple-700 border-purple-200',
    status: 'prototype',
    category: 'privacy',
    description: 'Consent-gated preference learning with owner-only taste summaries, editable controls, reset semantics, and strict explanation-layer separation.',
    keyFeatures: ['Explicit signals outrank implicit signals', 'Messages, photos, and protected traits are excluded', 'Owner-visible category summaries only', 'Reset clears taste but preserves safety records'],
    primarySurface: 'settings',
    entryPoints: [
      entry('settings', 'Open taste profile', 'Inspect and reset owner-only taste settings.', '/settings/taste-profile', true),
      entry('daily', 'Tune from Daily Picks', 'Use more and less signals without public objectification.', '/daily'),
    ],
    requiredConsent: ['private_taste'],
    aiFeatureKey: 'taste_profile',
    outputType: 'settings',
  }),
  defineSkill({
    id: 'private-recommendations',
    skillId: 'kesher-private-recommendations',
    title: 'Private Recommendations',
    shortTitle: 'Recommendations',
    subtitle: 'Permissioned Sharing & Privacy',
    icon: Users,
    color: 'bg-purple-100 text-purple-700 border-purple-200',
    status: 'prototype',
    category: 'privacy',
    description: 'Implements permissioned sharing, private taste profiles, staged disclosure patterns, and sensitive data exclusion schemas.',
    keyFeatures: ['Staged disclosure architecture', 'Sensitive data exclusion schemas', 'Consent flow design per sharing level', 'Private taste integration with recommendation engine'],
    primarySurface: 'daily',
    entryPoints: [
      entry('daily', 'Review recommendation controls', 'Keep Daily Picks finite and privacy-preserving.', '/daily', true),
      entry('settings', 'Manage private taste', 'Open owner-only recommendation settings.', '/settings/taste-profile'),
    ],
    requiredConsent: ['private_taste'],
    aiFeatureKey: 'taste_profile',
    outputType: 'settings',
  }),
  defineSkill({
    id: 'why-this-match',
    skillId: 'kesher-personality-why-match',
    title: 'Why This Match',
    shortTitle: 'Why Match',
    subtitle: 'Provenance-Labeled Explanations',
    icon: MessageSquare,
    color: 'bg-amber-100 text-amber-700 border-amber-200',
    status: 'prototype',
    category: 'personality',
    description: 'Source-chip UI, signal allowlist enforcement, safe formulation patterns, and anti-leakage controls for match explanations.',
    keyFeatures: ['Source chips on explanation items', 'Short explanations per match', 'No percentages, personality scores, or certainty claims', 'Deterministic fallback templates when Gemini fails'],
    primarySurface: 'daily',
    entryPoints: [
      entry('daily', 'Understand a Daily Pick', 'Explain visible overlap without hidden signals.', '/daily', true),
      entry('match', 'Understand this match', 'Save a gentle insight after matching.', '/inbox'),
      entry('profile', 'Review visible reasons', 'Open profile detail explanation context.', '/daily'),
    ],
    requiredConsent: ['match_context'],
    aiFeatureKey: 'why_match',
    outputType: 'insight',
  }),
  defineSkill({
    id: 'permissioned-sharing',
    skillId: 'kesher-permissioned-sharing',
    title: 'Permissioned Sharing',
    shortTitle: 'Sharing',
    subtitle: 'Share Cards & Mutual Consent',
    icon: Users,
    color: 'bg-pink-100 text-pink-700 border-pink-200',
    status: 'prototype',
    category: 'privacy',
    description: 'Basic and deeper share cards, recipient-scoped previews, deeper card requests, mutual reflection flow, and revocation cascades.',
    keyFeatures: ['Preview exactly what will be shared', 'Scope limited to summary, strengths, and communication notes', 'Temporary sharing by default', 'Revoke path in two taps with cascades'],
    primarySurface: 'match',
    entryPoints: [
      entry('match', 'Preview a share card', 'Show exactly what would be shared before consent.', '/inbox', true),
      entry('chat', 'Request mutual context', 'Keep personality sharing permissioned in chat.', '/inbox'),
    ],
    requiredConsent: ['mutual_consent'],
    outputType: 'settings',
  }),
  defineSkill({
    id: 'compatibility-reflection',
    skillId: 'kesher-compatibility-reflection',
    title: 'Compatibility Reflection',
    shortTitle: 'Reflection',
    subtitle: 'Bilateral Personality Insights',
    icon: Heart,
    color: 'bg-rose-100 text-rose-700 border-rose-200',
    status: 'prototype',
    category: 'personality',
    description: 'Values alignment, communication lens, friction forecast, and growth-edge reflections with bilateral consent and anti-pattern enforcement.',
    keyFeatures: ['Mutual consent required from both parties', 'Reflection is a conversation starter only', 'No numeric fit ratings or certainty claims', 'Either party can remove the reflection'],
    primarySurface: 'match',
    entryPoints: [
      entry('match', 'Save match insight', 'Create a consent-aware reflection from a match sheet.', '/inbox', true),
      entry('chat', 'Open conversation lens', 'Use reflection without sending a message automatically.', '/inbox'),
    ],
    requiredConsent: ['mutual_consent'],
    aiFeatureKey: 'compatibility_reflection',
    safetyLevel: 'medium',
    outputType: 'reflection',
  }),
  defineSkill({
    id: 'explainable-ai',
    skillId: 'kesher-explainable-ai',
    title: 'Explainable AI',
    shortTitle: 'Explainability',
    subtitle: 'Trust Language & Transparency',
    icon: Lightbulb,
    color: 'bg-yellow-100 text-yellow-700 border-yellow-200',
    status: 'prototype',
    category: 'governance',
    description: 'Governs how Kesher AI communicates reasoning with whitelisted signals, privacy protection, and deterministic fallback behavior.',
    keyFeatures: ['Signal whitelist enforcement', 'Generative and deterministic fallback pipeline', 'Hebrew-first trust-building copy', 'Management controls alongside explanations'],
    primarySurface: 'ai-trust',
    entryPoints: [
      entry('ai-trust', 'Open explanation controls', 'See which AI features explain decisions.', '/settings/ai-trust', true),
      entry('daily', 'Inspect explanation chips', 'Review why-match copy in Daily Picks.', '/daily'),
    ],
    requiredConsent: ['none'],
    outputType: 'settings',
  }),
  defineSkill({
    id: 'filtering-marketplace',
    skillId: 'kesher-filtering-marketplace',
    title: 'Filtering & Marketplace',
    shortTitle: 'Filters',
    subtitle: 'Grammar, Reciprocal Ranking & Fairness',
    icon: ShoppingBag,
    color: 'bg-lime-100 text-lime-700 border-lime-200',
    status: 'prototype',
    category: 'ux',
    description: 'Filtering grammar, marketplace mechanics, reciprocal ranking, Daily Picks versus Explore boundaries, and anti-starvation exposure fairness.',
    keyFeatures: ['Hard dealbreaker versus soft preference grammar', 'Reciprocal scoring based on mutual interest', 'Daily Picks are curated and limited while Explore is user-directed', 'Impression caps and new-user boost for fairness'],
    primarySurface: 'explore',
    entryPoints: [
      entry('explore', 'Tune Explore filters', 'Adjust filters without turning people into scores.', '/explore', true),
      entry('daily', 'Reflect on Daily Picks', 'Use finite-picks reflection for calmer discovery.', '/daily'),
    ],
    requiredConsent: ['none'],
    outputType: 'settings',
  }),
  defineSkill({
    id: 'learned-taste',
    skillId: 'kesher-learned-taste',
    title: 'Learned Taste',
    shortTitle: 'Learned Taste',
    subtitle: 'Implicit & Explicit Preference Learning',
    icon: Activity,
    color: 'bg-green-100 text-green-700 border-green-200',
    status: 'prototype',
    category: 'ux',
    description: 'Event taxonomy, taste-weight calculation, dual memory, and hybrid on-device/server architecture for privacy-preserving preference learning.',
    keyFeatures: ['Explicit controls always outrank implicit signals', 'Fast and slow memory windows', 'Hybrid on-device cache and canonical server state', 'Messages, photos, and exact location excluded'],
    primarySurface: 'daily',
    entryPoints: [
      entry('daily', 'Adjust taste gently', 'Use more and less signals from Daily Picks.', '/daily', true),
      entry('settings', 'Reset learned taste', 'Open private taste controls.', '/settings/taste-profile'),
    ],
    requiredConsent: ['private_taste'],
    aiFeatureKey: 'taste_profile',
    outputType: 'settings',
  }),
  defineSkill({
    id: 'maps-date-planner',
    skillId: 'kesher-maps-date-planner',
    title: 'Maps Date Planner',
    shortTitle: 'Date Planner',
    subtitle: 'Google Maps-Grounded Date Planning',
    icon: Map,
    color: 'bg-cyan-100 text-cyan-700 border-cyan-200',
    status: 'prototype',
    category: 'platform',
    description: 'Google Maps-grounded date suggestions with fairness preview, observance-aware scheduling, safe-venue defaults, and accessibility concierge.',
    keyFeatures: ['Midpoint venue planning with travel-time fairness preview', 'Shabbat, kashrut, and holiday awareness', 'Coarse locations only, never exact address', 'Manual send only and never auto-sent to a match'],
    primarySurface: 'match',
    entryPoints: [
      entry('match', 'Plan a reviewed date', 'Draft safe venue options for a matched pair.', '/inbox', true),
      entry('chat', 'Draft date ideas', 'Place reviewed date ideas near the composer, never auto-send.', '/inbox'),
      entry('safety', 'Review date safety', 'Open date-safety planning guidance.', '/settings/safety'),
    ],
    requiredConsent: ['match_context'],
    aiFeatureKey: 'date_planner',
    safetyLevel: 'medium',
    outputType: 'draft',
  }),
  defineSkill({
    id: 'pacing-coach',
    skillId: 'kesher-pacing-coach',
    title: 'Pacing Coach',
    shortTitle: 'Pacing',
    subtitle: 'Anti-Burnout Discovery',
    icon: Coffee,
    color: 'bg-green-100 text-green-700 border-green-200',
    status: 'prototype',
    category: 'ux',
    description: 'Gentle dismissible pacing interventions based on session length, action velocity, and pass streaks. Never blocks access or uses pressure.',
    keyFeatures: ['Deterministic triggers with no identity inference', 'Always dismissible in one tap', 'Gemini failure produces no modal', 'Rate-limited supportive nudges'],
    primarySurface: 'daily',
    entryPoints: [
      entry('daily', 'Resume pacing reflection', 'Reflect after a finite Daily Picks session.', '/daily', true),
      entry('chat', 'Check conversation pace', 'Suggest calmer pacing without sending anything.', '/inbox'),
    ],
    requiredConsent: ['none'],
    aiFeatureKey: 'pacing_coach',
    outputType: 'reflection',
  }),
  defineSkill({
    id: 'ai-runtime-governance',
    skillId: 'kesher-ai-governance',
    title: 'AI Runtime Governance',
    shortTitle: 'AI Governance',
    subtitle: 'Vertex AI & ZDR Controls',
    icon: Sparkles,
    color: 'bg-slate-100 text-slate-700 border-slate-200',
    status: 'prototype',
    category: 'governance',
    description: 'Provider routing decisions, zero-data-retention controls, structured outputs, App Check, feature registry, and provenance ledger.',
    keyFeatures: ['Vertex AI for personality-sensitive routes', 'Firebase AI Logic for non-sensitive features', 'Feature registry starts sensitive flags off', 'Provenance ledger schema per AI output'],
    primarySurface: 'ai-trust',
    entryPoints: [
      entry('ai-trust', 'Inspect AI controls', 'Review which skills use AI and what data they can use.', '/settings/ai-trust', true),
      entry('admin', 'Open AI ops', 'Internal governance view for operators only.', '/admin/ai-ops'),
    ],
    requiredConsent: ['admin_only'],
    safetyLevel: 'internal',
    outputType: 'reference',
  }),
  defineSkill({
    id: 'ai-feature-modules',
    skillId: 'kesher-ai-feature-modules',
    title: 'AI Feature Modules',
    shortTitle: 'AI Modules',
    subtitle: 'F01-F11 Feature Registry',
    icon: GitBranch,
    color: 'bg-slate-100 text-slate-700 border-slate-200',
    status: 'prototype',
    category: 'governance',
    description: 'AI feature modules for bio coaching, values phrasing, taste profiles, Daily Picks, match explanations, pacing, moderation, scam detection, report intake, disclosure, and personality coaching.',
    keyFeatures: ['Feature registry with risk tiers', 'Model routing per feature', 'Consent requirements per feature', 'Data inputs and exclusions documented per module'],
    primarySurface: 'ai-trust',
    entryPoints: [
      entry('ai-trust', 'Review AI feature list', 'Control visible AI modules and data scopes.', '/settings/ai-trust', true),
      entry('profile-builder', 'Use profile coach module', 'Run profile completeness without sending hidden data.', '/profile/edit'),
    ],
    requiredConsent: ['ai_assist'],
    outputType: 'settings',
  }),
  defineSkill({
    id: 'gemini-integration',
    skillId: 'kesher-gemini-integration',
    title: 'Gemini Integration',
    shortTitle: 'Gemini',
    subtitle: 'Core Patterns & Server-Side Proxy',
    icon: Cpu,
    color: 'bg-blue-100 text-blue-700 border-blue-200',
    status: 'prototype',
    category: 'platform',
    description: 'Core Gemini patterns for structured outputs, function calling, grounding, system instructions, server-side proxy architecture, and trust-preserving interactions.',
    keyFeatures: ['Server-side only with no API keys in the client bundle', 'Structured JSON output for every feature', 'System instruction templates per feature class', 'Prompt sanitization before every call'],
    primarySurface: 'ai-trust',
    entryPoints: [
      entry('ai-trust', 'Inspect server-side AI', 'Explain that AI calls are server-routed.', '/settings/ai-trust', true),
      entry('admin', 'Open AI operations', 'Internal operator view of AI routes.', '/admin/ai-ops'),
    ],
    requiredConsent: ['admin_only'],
    safetyLevel: 'internal',
    outputType: 'reference',
  }),
  defineSkill({
    id: 'low-latency-ai',
    skillId: 'kesher-low-latency-ai',
    title: 'Low-Latency AI',
    shortTitle: 'Latency',
    subtitle: 'Server-Side Proxy Architecture',
    icon: Zap,
    color: 'bg-yellow-100 text-yellow-700 border-yellow-200',
    status: 'prototype',
    category: 'platform',
    description: 'Server-side AI proxy architecture for low-latency responses with model routing, streaming patterns, feature registry, and policy-aware request handling.',
    keyFeatures: ['Latency targets per feature tier', 'Streaming for longer outputs', 'Model routing matrix by sensitivity and cost', 'Policy-aware request gating'],
    primarySurface: 'ai-trust',
    entryPoints: [
      entry('ai-trust', 'Review AI responsiveness', 'Show fast-path versus careful-path controls.', '/settings/ai-trust', true),
      entry('admin', 'Inspect route health', 'Operator route and latency reference.', '/admin/ai-ops'),
    ],
    requiredConsent: ['admin_only'],
    safetyLevel: 'internal',
    outputType: 'reference',
  }),
  defineSkill({
    id: 'high-thinking-routing',
    skillId: 'kesher-high-thinking-routing',
    title: 'High-Thinking Routing',
    shortTitle: 'Thinking',
    subtitle: 'Gemini Thinking Mode Strategy',
    icon: Brain,
    color: 'bg-indigo-100 text-indigo-700 border-indigo-200',
    status: 'prototype',
    category: 'platform',
    description: 'Routing strategy for high-thinking model modes, including when to enable thinking controls, hybrid fast plus careful paths, and evaluation design.',
    keyFeatures: ['Thinking configuration guidance', 'Fast path plus careful-path hybrid pattern', 'A/B test framework for thinking-enabled features', 'Cost and latency trade-off matrix'],
    primarySurface: 'ai-trust',
    entryPoints: [
      entry('ai-trust', 'Review careful AI mode', 'Explain when Kesher uses deeper reasoning.', '/settings/ai-trust', true),
      entry('admin', 'Open experiment controls', 'Operator-only experiment settings.', '/admin/experiments'),
    ],
    requiredConsent: ['admin_only'],
    safetyLevel: 'internal',
    outputType: 'reference',
  }),
  defineSkill({
    id: 'grounded-search',
    skillId: 'kesher-grounded-search',
    title: 'Grounded Search',
    shortTitle: 'Search Grounding',
    subtitle: 'Google Search Integration',
    icon: Search,
    color: 'bg-teal-100 text-teal-700 border-teal-200',
    status: 'gated',
    operationalStatus: 'gated_dependency',
    category: 'platform',
    description: 'Search grounding for Q&A, event discovery, safety resources, citation rendering, and URL-context features through server-side AI routes.',
    keyFeatures: ['Search-grounded Q&A with citations', 'Event discovery for date planning', 'Safety center resource grounding', 'Citation UI with source chips'],
    primarySurface: 'safety',
    entryPoints: [
      entry('safety', 'Open grounded safety help', 'Use cited safety resources without exposing private chat context.', '/settings/safety', true),
      entry('match', 'Ground date resources', 'Support reviewed date planning.', '/inbox'),
    ],
    requiredConsent: ['none'],
    aiFeatureKey: 'safety_advice',
    outputType: 'insight',
    demoModeBehavior: 'Runs as a cited safety/date-resource fixture unless server-side search grounding is available.',
    dataInputs: ['safety question', 'coarse date-planning context'],
    dataExclusions: ['private messages', 'exact addresses', 'raw reports', 'hidden ranking weights'],
  }),
  defineSkill({
    id: 'image-analysis',
    skillId: 'kesher-image-analysis',
    title: 'Image Analysis',
    shortTitle: 'Photo Checks',
    subtitle: 'Trust-Forward Photo Checks',
    icon: Image,
    color: 'bg-rose-100 text-rose-700 border-rose-200',
    status: 'gated',
    operationalStatus: 'gated_dependency',
    category: 'governance',
    description: 'Trust-forward image analysis for photo readiness checks, content moderation assistance, accessibility alt text, and moderation appeal support.',
    keyFeatures: ['Photo readiness checks, not attractiveness scoring', 'Content moderation assistance for human review', 'Accessibility alt-text generation', 'No attractiveness, race, or protected-trait inference'],
    primarySurface: 'profile-builder',
    entryPoints: [
      entry('profile-builder', 'Check photo readiness', 'Review profile photos for safety and clarity.', '/profile/edit', true),
      entry('safety', 'Review photo safety', 'Keep photo reporting guidance visible.', '/settings/safety'),
    ],
    requiredConsent: ['photo_analysis'],
    safetyLevel: 'medium',
    aiFeatureKey: 'visual_icebreaker',
    outputType: 'insight',
    demoModeBehavior: 'Shows photo-readiness and alt-text guidance only. It never scores attractiveness or infers protected traits.',
    dataInputs: ['member-selected profile photo'],
    dataExclusions: ['appearance_ranking', 'romantic_appeal_inference', 'protected_trait_inference', 'face recognition', 'raw moderation evidence'],
    testsRequired: ['image_analysis_no_attractiveness', 'protected_trait_inference_blocked', 'launcher_gated_fallback'],
  }),
  defineSkill({
    id: 'voice-integration',
    skillId: 'kesher-voice-integration',
    title: 'Voice Integration',
    shortTitle: 'Voice',
    subtitle: 'Gemini Live API',
    icon: Mic,
    color: 'bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200',
    status: 'gated',
    operationalStatus: 'gated_dependency',
    category: 'platform',
    description: 'Voice AI integration using Gemini Live API patterns for ephemeral authentication, push-to-talk interfaces, and accessibility-focused voice features.',
    keyFeatures: ['Gemini Live API WebSocket session patterns', 'Ephemeral token auth only', 'Push-to-talk UI with accessibility labels', 'Graceful fallback when voice is unavailable'],
    primarySurface: 'chat',
    entryPoints: [
      entry('chat', 'Review voice prototype', 'Demo-disabled voice reference in chat context.', '/inbox', true),
      entry('ai-trust', 'Check voice permissions', 'Keep voice opt-in controls explicit.', '/settings/ai-trust'),
    ],
    requiredConsent: ['ai_assist'],
    aiFeatureKey: 'voice_reflection',
    outputType: 'reference',
    demoModeBehavior: 'Starts a reference panel only. No microphone session is opened in the prototype.',
  }),
  defineSkill({
    id: 'google-ai-studio-app-builder',
    skillId: 'google-ai-studio-app-builder',
    title: 'AI Studio App Builder',
    shortTitle: 'AI Studio',
    subtitle: 'Rapid Prototype Composition',
    icon: Cpu,
    color: 'bg-blue-100 text-blue-700 border-blue-200',
    status: 'prototype',
    category: 'platform',
    description: 'Captures AI Studio app-builder workflows for composing and iterating feature prototypes aligned to Kesher constraints.',
    keyFeatures: ['Prototype workflow guidance', 'Rapid feature scaffolding', 'Iteration loop for concept validation', 'Alignment with trust-forward constraints'],
    primarySurface: 'admin',
    entryPoints: [
      entry('admin', 'Open prototype controls', 'Operator-facing prototype reference.', '/admin/experiments', true),
      entry('skills', 'Review builder skill', 'Keep prototype builder context in the Skills library.', '/skills'),
    ],
    requiredConsent: ['admin_only'],
    safetyLevel: 'internal',
    outputType: 'reference',
  }),
  defineSkill({
    id: 'sparkmatch-dating-app-skill',
    skillId: 'sparkmatch-dating-app-skill',
    title: 'SparkMatch Dating App',
    shortTitle: 'Reference App',
    subtitle: 'Reference App Patterns',
    icon: Heart,
    color: 'bg-pink-100 text-pink-700 border-pink-200',
    status: 'prototype',
    operationalStatus: 'partially_operational',
    category: 'platform',
    description: 'Reference skill package for dating-app flow patterns used as a comparative blueprint for feature-level UX and product decisions.',
    keyFeatures: ['Dating flow reference patterns', 'Feature-level UX blueprinting', 'Prototype parity checks', 'Decision-support examples'],
    primarySurface: 'admin',
    entryPoints: [
      entry('admin', 'Review reference patterns', 'Operator-only comparison patterns.', '/admin/experiments', true),
      entry('explore', 'Apply calm flow checks', 'Use reference patterns only through Kesher safety constraints.', '/explore'),
    ],
    requiredConsent: ['admin_only'],
    safetyLevel: 'internal',
    outputType: 'reference',
    demoModeBehavior: 'Runs as a Kesher-safe pattern checker. It does not import hookup-first, scoring, or casino mechanics.',
  }),
  defineSkill({
    id: 'video-generator',
    skillId: 'video-generator',
    title: 'Video Generator',
    shortTitle: 'Video',
    subtitle: 'Multimodal Prototype Utility',
    icon: Image,
    color: 'bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200',
    status: 'gated',
    operationalStatus: 'gated_dependency',
    category: 'platform',
    description: 'Prototype utility for video-generation workflows where multimodal outputs are needed for demos, storytelling, and concept validation.',
    keyFeatures: ['Video generation workflow reference', 'Multimodal demo support', 'Concept storytelling assets', 'Prototype-ready output guidance'],
    primarySurface: 'admin',
    entryPoints: [
      entry('admin', 'Review video controls', 'Operator-only reference; no member-facing fake generation.', '/admin/experiments', true),
      entry('ai-trust', 'Review media AI policy', 'Show media AI as controlled and opt-in only.', '/settings/ai-trust'),
    ],
    requiredConsent: ['admin_only'],
    safetyLevel: 'internal',
    aiFeatureKey: 'visual_icebreaker',
    outputType: 'reference',
    demoModeBehavior: 'Starts a reference state only. The prototype does not generate videos.',
  }),
  defineSkill({
    id: 'system-prompt',
    skillId: 'kesher-system-prompt',
    title: 'System Prompt',
    shortTitle: 'Prompt Policy',
    subtitle: 'Kesher OS Master Framework',
    icon: BookOpen,
    color: 'bg-gray-100 text-gray-700 border-gray-200',
    status: 'prototype',
    category: 'governance',
    description: 'Kesher OS master framework for strategic evaluation, architecture design, execution planning, run modes, rubrics, and product red lines.',
    keyFeatures: ['Master system instruction architecture', 'Run mode switching', 'Evaluation rubrics per feature class', 'Product principles and red-line enforcement'],
    primarySurface: 'ai-trust',
    entryPoints: [
      entry('ai-trust', 'Review AI principles', 'Show that AI assists and never impersonates.', '/settings/ai-trust', true),
      entry('admin', 'Open operator controls', 'Operator-only prompt governance reference.', '/admin/ai-ops'),
    ],
    requiredConsent: ['admin_only'],
    safetyLevel: 'internal',
    outputType: 'reference',
  }),
  defineSkill({
    id: 'calm-ux',
    skillId: 'kesher-calm-ux',
    title: 'Calm UX',
    shortTitle: 'Calm UX',
    subtitle: 'Hebrew-First & Anti-Casino Design',
    icon: Palette,
    color: 'bg-stone-100 text-stone-700 border-stone-200',
    status: 'prototype',
    category: 'ux',
    description: 'Premium calm UX strategy for Hebrew-first RTL design, accessibility standards, and differentiation from pressure-based dating mechanics.',
    keyFeatures: ['Hebrew RTL layout system', 'No infinite-scroll pressure mechanics', 'Finite daily discovery batch', 'Calm color palette and typography system'],
    primarySurface: 'daily',
    entryPoints: [
      entry('daily', 'Reflect on calmer discovery', 'Support finite Daily Picks and mindful pacing.', '/daily', true),
      entry('explore', 'Review Explore calm controls', 'Keep Explore controlled and filter-led.', '/explore'),
    ],
    requiredConsent: ['none'],
    outputType: 'reflection',
  }),
  defineSkill({
    id: 'psychometric-validation',
    skillId: 'kesher-psychometric-validation',
    title: 'Psychometric Validation',
    shortTitle: 'Validation',
    subtitle: 'ESEM/Bifactor Pipeline',
    icon: Scale,
    color: 'bg-cyan-100 text-cyan-700 border-cyan-200',
    status: 'prototype',
    category: 'personality',
    description: 'Adaptation lab, reliability analysis, test-retest stability, response quality audit, measurement invariance, and incremental validity testing.',
    keyFeatures: ['ESEM and bifactor modeling pipeline', 'Measurement invariance across Hebrew and English', 'Test-retest reliability targets', 'Incremental validity over explicit preferences'],
    primarySurface: 'profile-builder',
    entryPoints: [
      entry('profile-builder', 'Validate assessment quality', 'Show quality checks around assessment completion.', '/settings/personality', true),
      entry('ai-trust', 'Review personality safeguards', 'Open AI transparency for personality features.', '/settings/ai-trust'),
    ],
    requiredConsent: ['profile_data'],
    outputType: 'reference',
  }),
  defineSkill({
    id: 'dark-pattern-audit',
    skillId: 'kesher-dark-pattern-audit',
    title: 'Dark Pattern Audit',
    shortTitle: 'Pattern Audit',
    subtitle: 'EU Taxonomy & Comprehension Tests',
    icon: FileCheck,
    color: 'bg-orange-100 text-orange-700 border-orange-200',
    status: 'prototype',
    category: 'governance',
    description: 'Dark-pattern taxonomy audit, comprehension benchmarks, regret and surprise measures, and premium-boundary ethics verification.',
    keyFeatures: ['EU dark-pattern taxonomy', 'Comprehension test benchmarks', 'Regret and surprise measurement protocol', 'Premium boundary ethics review'],
    primarySurface: 'ai-trust',
    entryPoints: [
      entry('ai-trust', 'Audit consent design', 'Check AI and privacy controls for coercive patterns.', '/settings/ai-trust', true),
      entry('safety', 'Review safety access', 'Keep report and block actions direct.', '/settings/safety'),
    ],
    requiredConsent: ['none'],
    outputType: 'reference',
  }),
  defineSkill({
    id: 'personality-delivery',
    skillId: 'kesher-personality-delivery',
    title: 'Personality Delivery',
    shortTitle: 'Delivery',
    subtitle: 'Verification & Release Workflow',
    icon: GitBranch,
    color: 'bg-slate-100 text-slate-700 border-slate-200',
    status: 'prototype',
    category: 'governance',
    description: 'Coordinates implementation handoff, verification, review, CI, and deployment checks for personality-related features across delivery paths.',
    keyFeatures: ['Verification matrix before release', 'Browser and CI check orchestration', 'Platform-aware delivery decisions', 'Explicit approval stop points for risky operations'],
    primarySurface: 'admin',
    entryPoints: [
      entry('admin', 'Open release controls', 'Operator-only delivery and verification view.', '/admin/experiments', true),
      entry('skills', 'Review release skill', 'Keep skill delivery visible in the Skills library.', '/skills'),
    ],
    requiredConsent: ['admin_only'],
    safetyLevel: 'internal',
    outputType: 'reference',
  }),
  defineSkill({
    id: 'identity-verification',
    skillId: 'kesher-identity-verification',
    title: 'Identity Verification',
    shortTitle: 'Identity',
    subtitle: 'Auth & Verified Profile Signals',
    icon: Fingerprint,
    color: 'bg-blue-100 text-blue-700 border-blue-200',
    status: 'gated',
    category: 'governance',
    description: 'Production auth, profile verification, anti-impersonation review, pause/reactivation, account deletion, and privacy-rights entry points.',
    keyFeatures: ['Firebase Auth boundary', 'Verified profile signals without raw evidence disclosure', 'Pause, reactivate, export, correction, and deletion states', 'Manual review for impersonation and verification appeals'],
    primarySurface: 'onboarding',
    entryPoints: [
      entry('onboarding', 'Complete identity gates', 'Require profile, terms, and verification status before discovery.', '/profile/edit', true),
      entry('settings', 'Manage account rights', 'Expose pause, reactivation, export, correction, and deletion requests.', '/settings'),
      entry('safety', 'Review impersonation', 'Route suspicious identity issues into safety review.', '/settings/safety'),
    ],
    requiredConsent: ['profile_data'],
    safetyLevel: 'high',
    outputType: 'settings',
    prerequisites: ['Firebase Auth is configured for the production domain.', 'Identity evidence storage is isolated from profile display data.'],
    dataInputs: ['auth uid', 'profile completion state', 'verification status', 'account rights requests'],
    dataExclusions: ['raw identity documents', 'private taste state', 'raw personality answers', 'hidden ranking weights'],
    testsRequired: ['auth_required_for_discovery', 'verification_signal_no_raw_evidence', 'account_deletion_retention_split'],
  }),
  defineSkill({
    id: 'match-lifecycle',
    skillId: 'kesher-match-lifecycle',
    title: 'Match Lifecycle',
    shortTitle: 'Lifecycle',
    subtitle: 'Like, Match, Chat & History State',
    icon: Heart,
    color: 'bg-rose-100 text-rose-700 border-rose-200',
    status: 'prototype',
    category: 'ux',
    description: 'Like/pass/mutual-match/chat state machine with user-visible history and safe transitions across block, report, unmatch, pause, and delete.',
    keyFeatures: ['Explicit like, pass, match, message, block, report, and unmatch transitions', 'One conversation per mutual match', 'Draft-only AI openers and rephrases', 'Empty states for no picks, no matches, paused profiles, and blocked access'],
    primarySurface: 'daily',
    entryPoints: [
      entry('daily', 'Use Daily Picks lifecycle', 'Exercise like, pass, and match creation from Daily Picks.', '/daily', true),
      entry('explore', 'Use Explore lifecycle', 'Keep browse-driven actions consistent with Daily Picks.', '/explore'),
      entry('chat', 'Inspect chat transition', 'Verify conversations remain manual-send only.', '/inbox'),
    ],
    requiredConsent: ['match_context'],
    outputType: 'insight',
    dataInputs: ['profile id', 'interaction state', 'match status', 'conversation id'],
    dataExclusions: ['raw personality answers', 'hidden ranking weights', 'AI generated messages sent automatically'],
    testsRequired: ['like_pass_match_state_machine', 'block_report_unmatch_visibility', 'chat_draft_manual_send_only'],
  }),
  defineSkill({
    id: 'trust-safety-ops',
    skillId: 'kesher-trust-safety-ops',
    title: 'Trust & Safety Ops',
    shortTitle: 'Safety Ops',
    subtitle: 'Report Queue, Appeals & Audit Logs',
    icon: Shield,
    color: 'bg-red-100 text-red-700 border-red-200',
    status: 'prototype',
    category: 'governance',
    description: 'Report queue, moderation summaries, scam triage, photo checks, appeals, escalation, evidence retention, and operator audit logs.',
    keyFeatures: ['Report, block, unmatch, appeal, and escalation states', 'AI summaries that separate claims from evidence', 'Operator assignment and immutable action logs', 'Safety evidence isolated from recommendations and explanations'],
    primarySurface: 'admin',
    entryPoints: [
      entry('safety', 'File or review a report', 'Open member-facing safety actions.', '/settings/safety', true),
      entry('admin', 'Open safety queue', 'Inspect operator queue readiness from AI Ops.', '/admin/ai-ops'),
    ],
    requiredConsent: ['admin_only'],
    safetyLevel: 'internal',
    outputType: 'admin_summary',
    dataInputs: ['report reason', 'member-selected evidence', 'moderation summary', 'operator actions'],
    dataExclusions: ['private taste weights', 'unrelated private messages', 'raw identity documents outside evidence store'],
    testsRequired: ['report_queue_state_machine', 'ai_summary_claims_vs_evidence', 'audit_log_append_only'],
  }),
  defineSkill({
    id: 'notifications',
    skillId: 'kesher-notifications',
    title: 'Notifications',
    shortTitle: 'Notify',
    subtitle: 'Preference-Managed Delivery',
    icon: Bell,
    color: 'bg-indigo-100 text-indigo-700 border-indigo-200',
    status: 'planned',
    operationalStatus: 'reference_only',
    category: 'platform',
    description: 'Preference-managed email, push, and SMS notifications for matches, messages, safety events, date reminders, and consent/share changes.',
    keyFeatures: ['Category-level opt in and opt out', 'Safety and consent notices outrank engagement nudges', 'Sensitive detail redaction in previews', 'Provider callback, failure, and unsubscribe audit trail'],
    primarySurface: 'settings',
    entryPoints: [
      entry('settings', 'Configure notification preferences', 'Add category-level delivery controls.', '/settings', true),
      entry('admin', 'Review delivery health', 'Track delivery failures and provider callbacks.', '/admin/ai-ops'),
    ],
    requiredConsent: ['none'],
    outputType: 'settings',
    dataInputs: ['notification preference class', 'delivery channel', 'event type', 'provider callback status'],
    dataExclusions: ['sensitive match details in previews', 'report evidence in notifications', 'raw personality cards'],
    testsRequired: ['notification_preference_matrix', 'safety_notice_priority', 'preview_redaction'],
  }),
  defineSkill({
    id: 'subscription-entitlements',
    skillId: 'kesher-subscription-entitlements',
    title: 'Subscription Entitlements',
    shortTitle: 'Entitlements',
    subtitle: 'Premium Gates, Quotas & Billing',
    icon: ShoppingBag,
    color: 'bg-emerald-100 text-emerald-700 border-emerald-200',
    status: 'planned',
    operationalStatus: 'reference_only',
    category: 'platform',
    description: 'Pricing, premium gates, quotas, invoices, refunds, billing webhooks, and abuse-resistant trial entitlement checks.',
    keyFeatures: ['Server-side entitlement checks', 'Idempotent billing webhook handling', 'Trial abuse controls', 'Refund and cancellation state reconciliation'],
    primarySurface: 'settings',
    entryPoints: [
      entry('settings', 'Review premium state', 'Surface canonical entitlement state in settings.', '/settings', true),
      entry('admin', 'Audit entitlement gates', 'Inspect launch blockers and billing dependencies.', '/admin/ai-ops'),
    ],
    requiredConsent: ['none'],
    outputType: 'settings',
    dataInputs: ['subscription status', 'entitlement key', 'quota usage', 'billing webhook event'],
    dataExclusions: ['private dating content in billing records', 'safety evidence in payment metadata', 'identity documents'],
    testsRequired: ['server_entitlement_required', 'billing_webhook_idempotent', 'trial_cannot_bypass_safety_gates'],
  }),
  defineSkill({
    id: 'ai-evaluation-observability',
    skillId: 'kesher-ai-evaluation-observability',
    title: 'AI Evaluation & Observability',
    shortTitle: 'AI Evals',
    subtitle: 'Golden Tests, Red Teams & Route Health',
    icon: Activity,
    color: 'bg-cyan-100 text-cyan-700 border-cyan-200',
    status: 'prototype',
    category: 'governance',
    description: 'Golden tests, red-team prompts, latency budgets, output-quality dashboards, route health, and release-blocking model governance.',
    keyFeatures: ['Schema and privacy-exclusion tests for every AI route', 'Latency, fallback, validator, and prompt-version telemetry', 'Red-team prompts for leakage and unsafe automation', 'Release blockers for high-risk routes without provenance'],
    primarySurface: 'admin',
    entryPoints: [
      entry('admin', 'Open AI route health', 'View AI Ops status and product readiness gates.', '/admin/ai-ops', true),
      entry('ai-trust', 'Review user-facing AI controls', 'Connect route health to user controls.', '/settings/ai-trust'),
    ],
    requiredConsent: ['admin_only'],
    safetyLevel: 'internal',
    outputType: 'admin_summary',
    dataInputs: ['feature id', 'route id', 'model route', 'fallback status', 'validator result'],
    dataExclusions: ['raw user secrets', 'private messages outside tested payload fixtures', 'hidden ranking weights'],
    testsRequired: ['api_ai_contract_tests', 'redteam_private_signal_leakage', 'ai_latency_budget_smoke'],
  }),
  defineSkill({
    id: 'data-rights-retention',
    skillId: 'kesher-data-rights-retention',
    title: 'Data Rights & Retention',
    shortTitle: 'Data Rights',
    subtitle: 'Export, Delete, Retain & Revoke',
    icon: FileCheck,
    color: 'bg-stone-100 text-stone-700 border-stone-200',
    status: 'prototype',
    category: 'privacy',
    description: 'Export, correction, deletion, retention windows, evidence separation, privacy-rights audit trails, and share revocation cascades.',
    keyFeatures: ['Export, correction, deletion, reset, and revocation request states', 'Separate retention rules for taste, personality, messages, safety, and billing', 'Taste reset that preserves required safety evidence', 'Recipient-visible share revocation cascades'],
    primarySurface: 'settings',
    entryPoints: [
      entry('settings', 'Manage data rights', 'Expose rights requests from account settings.', '/settings', true),
      entry('ai-trust', 'Review AI data controls', 'Connect taste and personality reset/delete controls.', '/settings/ai-trust'),
      entry('admin', 'Audit retention status', 'Verify completion and failure states in operator views.', '/admin/ai-ops'),
    ],
    requiredConsent: ['profile_data', 'private_taste'],
    safetyLevel: 'high',
    outputType: 'settings',
    dataInputs: ['rights request type', 'data domain', 'retention class', 'request status'],
    dataExclusions: ['safety evidence erased by taste reset', 'billing records mixed with dating content', 'raw personality answers in exports without explicit owner request'],
    testsRequired: ['export_delete_request_status', 'retention_policy_domain_split', 'share_revocation_cascade'],
  }),
  defineSkill({
    id: 'release-readiness',
    skillId: 'kesher-release-readiness',
    title: 'Release Readiness',
    shortTitle: 'Release',
    subtitle: 'CI, Smoke Tests, Rollback & Monitoring',
    icon: GitBranch,
    color: 'bg-slate-100 text-slate-700 border-slate-200',
    status: 'prototype',
    category: 'governance',
    description: 'CI, smoke tests, deployment checklist, rollback, preview verification, monitoring, and launch-blocker tracking for the full Kesher product.',
    keyFeatures: ['Launch gates for auth, discovery, safety, AI, payments, notifications, data rights, and observability', 'Preview and production smoke checks', 'Rollback and incident response steps', 'Release blockers shown in operator dashboards'],
    primarySurface: 'admin',
    entryPoints: [
      entry('admin', 'Open release gates', 'View launch blockers in AI Ops.', '/admin/ai-ops', true),
      entry('skills', 'Review product readiness', 'Inspect product completion gates from the Skills Hub.', '/skills'),
      entry('settings', 'Review trust readiness', 'Connect release gates to member-facing controls.', '/settings/ai-trust'),
    ],
    requiredConsent: ['admin_only'],
    safetyLevel: 'internal',
    outputType: 'reference',
    dataInputs: ['CI result', 'smoke result', 'deployment metadata', 'launch gate status'],
    dataExclusions: ['secrets in logs', 'raw production user data in release reports', 'private message payloads'],
    testsRequired: ['ci_required_checks', 'prototype_smoke_routes', 'rollback_runbook_present'],
  }),
];

export const SKILL_DEFINITIONS = SKILLS;

export const SKILL_COUNTS = {
  live: SKILLS.filter((skill) => skill.status === 'live').length,
  prototype: SKILLS.filter((skill) => skill.status === 'prototype').length,
  gated: SKILLS.filter((skill) => skill.status === 'gated').length,
  planned: SKILLS.filter((skill) => skill.status === 'planned').length,
};

export const CATEGORY_LABELS: Record<'all' | SkillCategory, string> = {
  all: 'All',
  personality: 'Personality',
  privacy: 'Privacy & Consent',
  governance: 'Governance',
  ux: 'UX & Discovery',
  platform: 'Platform & AI',
};

export const SKILL_LIVE_ROUTES: Record<string, { path: string; label: string }> = SKILLS.reduce(
  (routes, skill) => {
    const point = skill.entryPoints.find((entryPoint) => entryPoint.route && entryPoint.featured)
      ?? skill.entryPoints.find((entryPoint) => entryPoint.route);
    if (point?.route) {
      routes[skill.id] = { path: point.route, label: point.label };
    }
    return routes;
  },
  {} as Record<string, { path: string; label: string }>,
);

export const getSkillById = (skillId: string) => SKILLS.find((skill) => skill.id === skillId);

export const getFeaturedSkills = () => SKILLS.filter((skill) => skill.featured);

export const getSkillsForSurface = (surface: SkillSurface, options?: { includeInternal?: boolean }) => (
  SKILLS.filter((skill) => {
    if (!options?.includeInternal && skill.safetyLevel === 'internal' && surface !== 'admin') return false;
    return skill.availableSurfaces.includes(surface) || skill.entryPoints.some((point) => point.surface === surface);
  })
);

export const getRecommendedSkillsForSurface = (
  surface: SkillSurface,
  options?: { limit?: number; includeInternal?: boolean },
) => getSkillsForSurface(surface, { includeInternal: options?.includeInternal })
  .sort((a, b) => Number(b.primarySurface === surface) - Number(a.primarySurface === surface))
  .slice(0, options?.limit ?? 4);

export const getSkillEntryPoint = (skill: SkillDefinition, surface: SkillSurface) => (
  skill.entryPoints.find((point) => point.surface === surface)
  ?? skill.entryPoints.find((point) => point.featured)
  ?? skill.entryPoints[0]
);
