export const FEATURE_FLAGS = {
  ENABLE_AI_BIO_COACH: true,
  ENABLE_AI_TASTE_PROFILE: true,
  ENABLE_AI_WHY_MATCH: true,
  ENABLE_AI_SAFETY_SCAN: true,
  ENABLE_AI_DATE_PLANNER: true,
  ENABLE_AI_SAFETY_ADVICE: true,
  ENABLE_AI_REPHRASE_MESSAGE: true,
  ENABLE_AI_GENERATE_OPENERS: true,
  ENABLE_AI_PROFILE_COMPLETENESS: true,
  ENABLE_AI_VOICE_REFLECTION: false, // Beta
  ENABLE_AI_MOD_SUMMARIZER: true, // Internal
  ENABLE_AI_VISUAL_ICEBREAKER: false, // Labs
  ENABLE_AI_PERSONALITY_PROFILE: true,
  ENABLE_AI_COMPATIBILITY_REFLECTION: true,
  ENABLE_AI_PACING_COACH: true,
};
