import { AIFeatureMetadata } from './types';
import { MODEL_REGISTRY } from './modelRegistry';
import { DATA_CLASS } from './dataClassification';

/**
 * AI Feature Registry
 * Central source of truth for all AI capabilities in Kesher.
 */

export const AI_FEATURE_REGISTRY: AIFeatureMetadata[] = [
  // CORE USER-FACING
  {
    id: 'bio_coach',
    name: 'Hebrew-first Bio Coach',
    category: 'core_enabled',
    user_visible: true,
    default_enabled: true,
    audience: 'user',
    runtime_model_route: 'optionalFastFallbackModel',
    actual_model_string: MODEL_REGISTRY.optionalFastFallbackModel,
    structured_output_used: true,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: false,
    requires_citation_ui: false,
    requires_human_confirmation: true,
    risk_level: 'low',
    data_inputs: ['user_raw_bio', 'tone_preference'],
    excluded_data: ['photos', 'precise_location'],
    notes: 'Helps users write authentic Hebrew bios.',
    capability_exception: false,
  },
  {
    id: 'taste_profile',
    name: 'Private Taste Profile Assistant',
    category: 'core_enabled',
    user_visible: true,
    default_enabled: true,
    audience: 'user',
    runtime_model_route: 'primaryStructuredModel',
    actual_model_string: MODEL_REGISTRY.primaryStructuredModel,
    structured_output_used: true,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: true,
    requires_citation_ui: false,
    requires_human_confirmation: true,
    risk_level: 'medium',
    data_inputs: ['likes', 'passes', 'dwell_time'],
    excluded_data: ['messages', 'real_name'],
    data_classes_allowed: [DATA_CLASS.PRIVATE_INFERRED],
    data_classes_forbidden: [DATA_CLASS.SYSTEM_ONLY_SAFETY],
    notes: 'Builds a private preference model from user behavior. Output is private to the user.',
    capability_exception: false,
  },
  {
    id: 'why_match',
    name: 'Why This Match',
    category: 'core_enabled',
    user_visible: true,
    default_enabled: true,
    audience: 'user',
    runtime_model_route: 'primaryStructuredModel',
    actual_model_string: MODEL_REGISTRY.primaryStructuredModel,
    structured_output_used: true,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: false,
    requires_citation_ui: false,
    requires_human_confirmation: false,
    risk_level: 'low',
    data_inputs: ['user_profile', 'candidate_profile', 'whitelisted_signals'],
    excluded_data: [
      'private_preferences',
      'private_taste_profile',
      'hidden_ranking_weights',
      'safety_flags',
      'raw_personality_scores',
      'behavioral_history',
      'inferred_protected_traits',
    ],
    data_classes_allowed: [DATA_CLASS.PUBLIC_PROFILE],
    data_classes_forbidden: [
      DATA_CLASS.PRIVATE_INFERRED,
      DATA_CLASS.SYSTEM_ONLY_SAFETY,
    ],
    notes: 'Explains values-based overlap using only whitelisted, user-visible signals.',
    capability_exception: false,
  },
  {
    id: 'safety_scan',
    name: 'Message Safety Scan',
    category: 'core_enabled',
    user_visible: false,
    default_enabled: true,
    audience: 'user',
    runtime_model_route: 'primaryStructuredModel',
    actual_model_string: MODEL_REGISTRY.primaryStructuredModel,
    structured_output_used: true,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: false,
    requires_citation_ui: false,
    requires_human_confirmation: false,
    risk_level: 'high',
    data_inputs: ['message_text'],
    excluded_data: ['user_identity'],
    data_classes_allowed: [DATA_CLASS.SYSTEM_ONLY_SAFETY],
    data_classes_forbidden: [DATA_CLASS.PRIVATE_INFERRED],
    notes: 'Scans messages for harmful content before sending. Output never leaks into match explanations.',
    capability_exception: false,
  },
  {
    id: 'date_planner',
    name: 'Midpoint Date Planner',
    category: 'core_enabled',
    user_visible: true,
    default_enabled: true,
    audience: 'user',
    runtime_model_route: 'mapsGroundedModel',
    actual_model_string: MODEL_REGISTRY.mapsGroundedModel,
    structured_output_used: true,
    function_calling_used: true,
    maps_used: true,
    search_used: false,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: true,
    requires_citation_ui: true,
    requires_human_confirmation: true,
    risk_level: 'medium',
    data_inputs: ['coarse_locations', 'preferences'],
    excluded_data: ['exact_addresses'],
    notes: 'Suggests safe public venues with Maps grounding.',
    capability_exception: true,
    exception_reason: 'Maps grounding is only supported in Gemini 2.5 series models.',
  },
  {
    id: 'safety_advice',
    name: 'Safety FAQ Assistant',
    category: 'core_enabled',
    user_visible: true,
    default_enabled: true,
    audience: 'user',
    runtime_model_route: 'primarySearchGroundedModel',
    actual_model_string: MODEL_REGISTRY.primarySearchGroundedModel,
    structured_output_used: false,
    function_calling_used: false,
    maps_used: false,
    search_used: true,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: false,
    requires_citation_ui: true,
    requires_human_confirmation: false,
    risk_level: 'low',
    data_inputs: ['user_question'],
    excluded_data: ['user_identity'],
    notes: 'Answers safety questions using Google Search grounding.',
    capability_exception: false,
  },
  {
    id: 'rephrase_message',
    name: 'Rephrase Message',
    category: 'core_enabled',
    user_visible: true,
    default_enabled: true,
    audience: 'user',
    runtime_model_route: 'optionalFastFallbackModel',
    actual_model_string: MODEL_REGISTRY.optionalFastFallbackModel,
    structured_output_used: false,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: false,
    requires_citation_ui: false,
    requires_human_confirmation: true,
    risk_level: 'low',
    data_inputs: ['message_text'],
    excluded_data: [
      'recipient_private_preferences',
      'private_taste_profile',
      'safety_flags',
    ],
    data_classes_allowed: [DATA_CLASS.PUBLIC_PROFILE],
    data_classes_forbidden: [
      DATA_CLASS.PRIVATE_INFERRED,
      DATA_CLASS.SYSTEM_ONLY_SAFETY,
    ],
    notes: 'Rewrite-first message coach. Requires a user draft; returns alternatives the user must explicitly send.',
    capability_exception: false,
  },
  {
    id: 'generate_openers',
    name: 'Generate Openers',
    category: 'core_enabled',
    user_visible: true,
    default_enabled: true,
    audience: 'user',
    runtime_model_route: 'optionalFastFallbackModel',
    actual_model_string: MODEL_REGISTRY.optionalFastFallbackModel,
    structured_output_used: false,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: false,
    requires_citation_ui: false,
    requires_human_confirmation: true,
    risk_level: 'low',
    data_inputs: ['profile_name', 'bio', 'prompt'],
    excluded_data: [],
    notes: 'Generates personalized openers based on profile.',
    capability_exception: false,
  },
  {
    id: 'profile_completeness',
    name: 'Profile Completeness Coach',
    category: 'core_enabled',
    user_visible: true,
    default_enabled: true,
    audience: 'user',
    runtime_model_route: 'primaryStructuredModel',
    actual_model_string: MODEL_REGISTRY.primaryStructuredModel,
    structured_output_used: true,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: false,
    requires_citation_ui: false,
    requires_human_confirmation: false,
    risk_level: 'low',
    data_inputs: ['user_profile'],
    excluded_data: [],
    notes: 'Analyzes profile completeness and quality.',
    capability_exception: false,
  },

  // BETA / OPT-IN
  {
    id: 'voice_reflection',
    name: 'Voice Reflection Journal',
    category: 'beta_opt_in',
    user_visible: true,
    default_enabled: false,
    audience: 'premium',
    runtime_model_route: 'liveModel',
    actual_model_string: MODEL_REGISTRY.liveModel,
    structured_output_used: false,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: true,
    file_search_used: false,
    live_api_used: true,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: true,
    requires_citation_ui: false,
    requires_human_confirmation: false,
    risk_level: 'medium',
    data_inputs: ['voice_audio'],
    excluded_data: [],
    notes: 'Private pre/post-date reflection.',
    capability_exception: true,
    exception_reason: 'Live API is only supported in specific models.',
  },

  // INTERNAL ONLY
  {
    id: 'mod_summarizer',
    name: 'Moderation Queue Summarizer',
    category: 'internal_only',
    user_visible: false,
    default_enabled: true,
    audience: 'internal',
    runtime_model_route: 'primaryStructuredModel',
    actual_model_string: MODEL_REGISTRY.primaryStructuredModel,
    structured_output_used: true,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: true,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: false,
    requires_citation_ui: false,
    requires_human_confirmation: true,
    risk_level: 'high',
    data_inputs: ['report_bundle', 'chat_history'],
    excluded_data: [],
    notes: 'Summarizes reports for human moderators.',
    capability_exception: false,
  },

  // LABS
  {
    id: 'visual_icebreaker',
    name: 'Visual Icebreaker Lab',
    category: 'labs_off_by_default',
    user_visible: true,
    default_enabled: false,
    audience: 'lab',
    runtime_model_route: 'imageGenerationModel',
    actual_model_string: MODEL_REGISTRY.imageGenerationModel,
    structured_output_used: false,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: true,
    requires_consent: true,
    requires_citation_ui: false,
    requires_human_confirmation: true,
    risk_level: 'low',
    data_inputs: ['prompt_text'],
    excluded_data: [],
    notes: 'Generates images for icebreakers. Demoted from core.',
    capability_exception: true,
    exception_reason: 'Image generation requires a specific model.',
  },
  {
    id: 'personality_profile',
    name: 'Personality Profile Interpreter',
    category: 'core_enabled',
    user_visible: true,
    default_enabled: true,
    audience: 'user',
    runtime_model_route: 'primaryStructuredModel',
    actual_model_string: MODEL_REGISTRY.primaryStructuredModel,
    structured_output_used: true,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: true,
    requires_citation_ui: false,
    requires_human_confirmation: false,
    risk_level: 'medium',
    data_inputs: ['bfas_percentiles'],
    excluded_data: ['raw_answers'],
    notes: 'Translates deterministic BFAS percentiles into a warm, Hebrew-first user profile.',
    capability_exception: false,
  },
  {
    id: 'compatibility_reflection',
    name: 'Compatibility Reflection Engine',
    category: 'core_enabled',
    user_visible: true,
    default_enabled: true,
    audience: 'user',
    runtime_model_route: 'primaryStructuredModel',
    actual_model_string: MODEL_REGISTRY.primaryStructuredModel,
    structured_output_used: true,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: false,
    requires_citation_ui: false,
    requires_human_confirmation: false,
    risk_level: 'medium',
    data_inputs: ['user_a_percentiles', 'user_b_percentiles'],
    excluded_data: [],
    notes: 'Compares two profiles and highlights friction and synergy without outputting a match score.',
    capability_exception: false,
  },
  {
    id: 'pacing_coach',
    name: 'Anti-Burnout Pacing Coach',
    category: 'core_enabled',
    user_visible: true,
    default_enabled: true,
    audience: 'user',
    runtime_model_route: 'primaryStructuredModel',
    actual_model_string: MODEL_REGISTRY.primaryStructuredModel,
    structured_output_used: true,
    function_calling_used: false,
    maps_used: false,
    search_used: false,
    url_context_used: false,
    files_used: false,
    file_search_used: false,
    live_api_used: false,
    code_execution_used: false,
    image_analysis_used: false,
    image_generation_used: false,
    requires_consent: false,
    requires_citation_ui: false,
    requires_human_confirmation: false,
    risk_level: 'low',
    data_inputs: ['session_length', 'swipe_velocity'],
    excluded_data: [],
    notes: 'Generates a gentle prompt to take a break.',
    capability_exception: false,
  }
];

export const getFeatureById = (id: string) => AI_FEATURE_REGISTRY.find(f => f.id === id);
