/**
 * Kesher Canonical Skill Registry
 * Single source of truth for all 14 AI skills.
 * Used by SkillsHub UI, admin AI governance page, and DB seed.
 */

export type SkillStatus = "working" | "demo_safe" | "blocked" | "needs_provider_setup";
export type SafetyLevel = "low" | "medium" | "high" | "critical";

export interface SkillDefinition {
  slug: string;
  title: string;
  shortTitle: string;
  category: "profile" | "discovery" | "messaging" | "safety" | "moderation";
  description: string;
  primarySurface: string;
  availableSurfaces: string[];
  trigger: string;
  userIntentServed: string;
  requiredInputs: string[];
  optionalInputs: string[];
  outputContract: Record<string, string>;
  privacyNote: string;
  safetyLevel: SafetyLevel;
  consentRequired: boolean;
  roleAvailability: ("user" | "moderator" | "admin")[];
  toolPolicy: string;
  approvalBoundary: string;
  failureModes: string[];
  fallbackBehavior: string;
  acceptanceCriteria: string[];
  status: SkillStatus;
}

export const SKILL_REGISTRY: SkillDefinition[] = [
  {
    slug: "bio-coach",
    title: "Bio / Profile Coach",
    shortTitle: "מאמן ביוגרפיה",
    category: "profile",
    description: "Provides gentle, optional suggestions to help users write an authentic, warm bio.",
    primarySurface: "Profile Builder",
    availableSurfaces: ["Profile Builder", "Profile Edit", "Skills Hub"],
    trigger: "User clicks 'Get AI suggestions' on bio field",
    userIntentServed: "Write a better bio without feeling judged",
    requiredInputs: ["currentBio"],
    optionalInputs: ["intent"],
    outputContract: { suggestions: "string[]", questions: "string[]", tone_note: "string" },
    privacyNote: "Bio text is sent to LLM. Not stored after response. No PII extraction.",
    safetyLevel: "low",
    consentRequired: false,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "LLM draft only. User must review and manually apply.",
    approvalBoundary: "User must click 'Apply' to use any suggestion.",
    failureModes: ["LLM hallucination of facts", "Overly generic suggestions"],
    fallbackBehavior: "Show empty state with manual tips if LLM fails.",
    acceptanceCriteria: [
      "Suggestions do not invent facts",
      "Suggestions are framed as optional",
      "Tone note is non-clinical",
      "Response is valid JSON matching schema",
    ],
    status: "working",
  },
  {
    slug: "profile-completeness",
    title: "Profile Completeness",
    shortTitle: "שלמות פרופיל",
    category: "profile",
    description: "Analyzes profile completeness and nudges users to fill missing sections.",
    primarySurface: "Home Dashboard",
    availableSurfaces: ["Home Dashboard", "Onboarding"],
    trigger: "Automatic on profile load",
    userIntentServed: "Know what to add to improve match quality",
    requiredInputs: ["profileFields"],
    optionalInputs: [],
    outputContract: { completionPct: "number", missingFields: "string[]", nextStep: "string" },
    privacyNote: "Computed client-side from profile fields. No LLM call.",
    safetyLevel: "low",
    consentRequired: false,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "Deterministic computation. No AI inference.",
    approvalBoundary: "No approval needed — informational only.",
    failureModes: ["Incorrect field detection"],
    fallbackBehavior: "Show generic 'Complete your profile' prompt.",
    acceptanceCriteria: [
      "Completion percentage is accurate",
      "Missing fields list is correct",
      "No false positives on required fields",
    ],
    status: "demo_safe",
  },
  {
    slug: "private-taste-profile",
    title: "Private Taste Profile",
    shortTitle: "פרופיל טעם פרטי",
    category: "discovery",
    description: "Builds a private, non-shared taste model from likes/passes to improve ranking.",
    primarySurface: "Daily Picks (background)",
    availableSurfaces: ["Daily Picks", "Explore"],
    trigger: "Automatic after 10+ likes/passes",
    userIntentServed: "See better matches without sharing private preferences",
    requiredInputs: ["likeHistory", "passHistory"],
    optionalInputs: [],
    outputContract: { tasteVector: "object", confidence: "number" },
    privacyNote: "Taste vector is private to user. Never shared or used in explanations.",
    safetyLevel: "medium",
    consentRequired: false,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "Computed server-side. Not exposed via API. Never used in match explanations.",
    approvalBoundary: "Fully automatic. User can reset via Trust Hub.",
    failureModes: ["Reinforcement of biases", "Cold-start inaccuracy"],
    fallbackBehavior: "Use recency-based ranking until sufficient data.",
    acceptanceCriteria: [
      "Taste vector never appears in API responses",
      "User can delete via Trust Hub",
      "Not used in Why Match explanations",
    ],
    status: "demo_safe",
  },
  {
    slug: "why-match",
    title: "Why This Match",
    shortTitle: "למה זה קשר?",
    category: "discovery",
    description: "Explains why two people were matched using only public profile signals.",
    primarySurface: "Daily Picks",
    availableSurfaces: ["Daily Picks", "Explore", "Match Detail"],
    trigger: "User clicks 'Why this match?' on a pick card",
    userIntentServed: "Understand the basis for a match before deciding",
    requiredInputs: ["matchId"],
    optionalInputs: [],
    outputContract: { explanation: "string", sharedSignals: "string[]", caveat: "string" },
    privacyNote: "Uses only public profile fields. No personality inference. No private data.",
    safetyLevel: "medium",
    consentRequired: false,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "Public signals only. Prohibited: personality scores, private answers, taste vector.",
    approvalBoundary: "Displayed inline. No action required.",
    failureModes: ["Hallucinated shared signals", "Over-claiming certainty"],
    fallbackBehavior: "Show generic 'You both share similar values' if LLM fails.",
    acceptanceCriteria: [
      "Explanation cites only public profile fields",
      "Caveat is always present",
      "No personality inference language",
      "No certainty claims",
    ],
    status: "working",
  },
  {
    slug: "message-safety-scan",
    title: "Message Safety Scan",
    shortTitle: "בדיקת בטיחות הודעה",
    category: "messaging",
    description: "Scans a draft message for potential red flags before sending.",
    primarySurface: "Chat Thread",
    availableSurfaces: ["Chat Thread"],
    trigger: "User clicks 'Check message' in chat compose area",
    userIntentServed: "Identify potential issues before sending",
    requiredInputs: ["messageContent"],
    optionalInputs: [],
    outputContract: { risk_level: "low|medium|high", flags: "string[]", advice: "string|null" },
    privacyNote: "Message content sent to LLM. Not stored. Scan is optional and user-initiated.",
    safetyLevel: "high",
    consentRequired: false,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "Conservative flagging. Never blocks sending. Advisory only.",
    approvalBoundary: "User sees result and decides whether to edit or send.",
    failureModes: ["False positives on benign content", "False negatives on subtle manipulation"],
    fallbackBehavior: "Show 'Unable to scan — please review manually' if LLM fails.",
    acceptanceCriteria: [
      "Never blocks message sending",
      "Low risk_level for clearly benign messages",
      "Advice is non-judgmental",
      "Response matches JSON schema",
    ],
    status: "working",
  },
  {
    slug: "rephrase",
    title: "Rephrase Message",
    shortTitle: "ניסוח מחדש",
    category: "messaging",
    description: "Provides 2-3 alternative phrasings for a draft message.",
    primarySurface: "Chat Thread",
    availableSurfaces: ["Chat Thread"],
    trigger: "User clicks 'Rephrase' on a draft message",
    userIntentServed: "Express the same idea more clearly or warmly",
    requiredInputs: ["draftMessage"],
    optionalInputs: [],
    outputContract: { alternatives: "string[]" },
    privacyNote: "Draft message sent to LLM. Not stored after response.",
    safetyLevel: "low",
    consentRequired: false,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "Never changes intent. Never adds romantic pressure.",
    approvalBoundary: "User selects an alternative or keeps original.",
    failureModes: ["Intent drift in rephrasing"],
    fallbackBehavior: "Show original message with 'Unable to rephrase' notice.",
    acceptanceCriteria: [
      "Alternatives preserve original intent",
      "No pressure language added",
      "At least 2 alternatives returned",
    ],
    status: "working",
  },
  {
    slug: "openers",
    title: "Conversation Openers",
    shortTitle: "פתיחות שיחה",
    category: "messaging",
    description: "Suggests 3 warm, genuine conversation openers based on a match's public profile.",
    primarySurface: "Match Detail",
    availableSurfaces: ["Match Detail", "Chat Thread"],
    trigger: "User clicks 'Get opener ideas' on a new match",
    userIntentServed: "Start a conversation naturally without feeling awkward",
    requiredInputs: ["matchProfileSummary"],
    optionalInputs: [],
    outputContract: { openers: "string[]" },
    privacyNote: "Uses only public profile summary. No private data.",
    safetyLevel: "low",
    consentRequired: false,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "Based on public info only. No pickup lines. No pressure.",
    approvalBoundary: "User selects and edits before sending.",
    failureModes: ["Generic openers not tailored to profile"],
    fallbackBehavior: "Show 3 generic warm openers.",
    acceptanceCriteria: [
      "Openers reference public profile details",
      "No pressure or pickup-line language",
      "3 openers returned",
    ],
    status: "working",
  },
  {
    slug: "date-ideas",
    title: "Date Ideas",
    shortTitle: "רעיונות לפגישה",
    category: "messaging",
    description: "Suggests 3 first-date ideas based on shared interests.",
    primarySurface: "Chat Thread",
    availableSurfaces: ["Chat Thread", "Match Detail"],
    trigger: "User clicks 'Date ideas' in chat",
    userIntentServed: "Plan a first date that feels natural and safe",
    requiredInputs: ["sharedInterests"],
    optionalInputs: [],
    outputContract: { ideas: "Array<{title, description, safetyNote}>" },
    privacyNote: "Shared interests sent to LLM. Not stored.",
    safetyLevel: "low",
    consentRequired: false,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "Always include safety note for first dates. Accessible, low-pressure ideas.",
    approvalBoundary: "User shares idea manually in chat.",
    failureModes: ["Inappropriate venue suggestions"],
    fallbackBehavior: "Show 3 generic safe first-date ideas.",
    acceptanceCriteria: [
      "Each idea includes a safetyNote",
      "Ideas are accessible and low-pressure",
      "3 ideas returned",
    ],
    status: "working",
  },
  {
    slug: "personality-summary",
    title: "Personality / Values Summary",
    shortTitle: "סיכום ערכים",
    category: "profile",
    description: "Writes a brief, warm summary of a user's publicly shared values.",
    primarySurface: "Profile Builder",
    availableSurfaces: ["Profile Builder", "Skills Hub"],
    trigger: "User clicks 'Summarize my values' in profile builder",
    userIntentServed: "Understand how their profile reads to others",
    requiredInputs: [],
    optionalInputs: ["bio", "intent", "observance"],
    outputContract: { summary: "string", caveat: "string" },
    privacyNote: "Uses only public profile fields. No personality inference.",
    safetyLevel: "medium",
    consentRequired: false,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "Non-clinical language only. Always include caveat. No diagnosis.",
    approvalBoundary: "Displayed to user only. Not shown to matches.",
    failureModes: ["Clinical-sounding language", "Over-interpretation"],
    fallbackBehavior: "Show generic 'Your profile shows warmth and intention' message.",
    acceptanceCriteria: [
      "No clinical terms",
      "Caveat always present",
      "Based only on provided fields",
    ],
    status: "working",
  },
  {
    slug: "pair-insight",
    title: "Pair Insight Report",
    shortTitle: "תובנת זוג",
    category: "discovery",
    description: "Provides a brief insight about potential dynamics between two matched users.",
    primarySurface: "Match Detail",
    availableSurfaces: ["Match Detail"],
    trigger: "User clicks 'Get pair insight' on a match (requires consent)",
    userIntentServed: "Understand potential compatibility before investing emotionally",
    requiredInputs: ["matchId"],
    optionalInputs: [],
    outputContract: { insight: "string", caveat: "string" },
    privacyNote: "Requires explicit consent. Uses only public profile fields. Never shared with match.",
    safetyLevel: "high",
    consentRequired: true,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "Public signals only. Non-clinical. Always include caveat. Never shared with match.",
    approvalBoundary: "Displayed only to requesting user after consent confirmation.",
    failureModes: ["Over-claiming compatibility", "Clinical-sounding language"],
    fallbackBehavior: "Show 'Unable to generate insight' if LLM fails.",
    acceptanceCriteria: [
      "Consent gate enforced server-side",
      "Caveat always present",
      "Not shared with match",
      "No clinical language",
    ],
    status: "working",
  },
  {
    slug: "pacing-intervention",
    title: "Pacing Intervention",
    shortTitle: "התערבות קצב",
    category: "messaging",
    description: "Detects unusually fast emotional escalation and offers a gentle reflection prompt.",
    primarySurface: "Chat Thread",
    availableSurfaces: ["Chat Thread"],
    trigger: "Automatic after detecting rapid escalation pattern",
    userIntentServed: "Avoid being swept up in fast-moving dynamics",
    requiredInputs: ["messageHistory"],
    optionalInputs: [],
    outputContract: { shouldIntervene: "boolean", prompt: "string|null" },
    privacyNote: "Message history analyzed server-side. Not stored beyond session.",
    safetyLevel: "high",
    consentRequired: false,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "Non-judgmental. Optional. User can dismiss. Never blocks sending.",
    approvalBoundary: "User sees gentle prompt and can dismiss or reflect.",
    failureModes: ["False positives on enthusiastic but healthy conversations"],
    fallbackBehavior: "No intervention shown if detection is uncertain.",
    acceptanceCriteria: [
      "Never blocks message sending",
      "Prompt is non-judgmental",
      "User can dismiss",
      "False positive rate < 10%",
    ],
    status: "demo_safe",
  },
  {
    slug: "safety-advice",
    title: "Safety Advice",
    shortTitle: "עצות בטיחות",
    category: "safety",
    description: "Provides general safety advice and resources for concerning situations.",
    primarySurface: "Safety Center",
    availableSurfaces: ["Safety Center", "Chat Thread"],
    trigger: "User clicks 'Get safety advice' in safety center",
    userIntentServed: "Get actionable safety guidance without judgment",
    requiredInputs: ["situation"],
    optionalInputs: [],
    outputContract: { advice: "string", resources: "string[]" },
    privacyNote: "Situation description sent to LLM. Not stored. General advice only.",
    safetyLevel: "critical",
    consentRequired: false,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "General advice only. Always recommend professional help for serious situations.",
    approvalBoundary: "Displayed inline. No action required.",
    failureModes: ["Overly generic advice", "Failure to recommend professional help"],
    fallbackBehavior: "Show static safety resources list.",
    acceptanceCriteria: [
      "Always includes professional help recommendation for serious situations",
      "Resources list is non-empty",
      "Advice is non-judgmental",
    ],
    status: "working",
  },
  {
    slug: "scam-warning",
    title: "Scam / Romance Fraud Warning",
    shortTitle: "אזהרת הונאה",
    category: "safety",
    description: "Detects common romance fraud patterns and warns the user.",
    primarySurface: "Chat Thread",
    availableSurfaces: ["Chat Thread", "Safety Center"],
    trigger: "Automatic pattern detection in message history",
    userIntentServed: "Avoid romance fraud without feeling paranoid",
    requiredInputs: ["messageHistory"],
    optionalInputs: [],
    outputContract: { riskLevel: "low|medium|high", patterns: "string[]", warning: "string|null" },
    privacyNote: "Message history analyzed server-side. Not stored beyond session.",
    safetyLevel: "critical",
    consentRequired: false,
    roleAvailability: ["user", "moderator", "admin"],
    toolPolicy: "Conservative flagging. Never blocks. Advisory only. Always recommend reporting.",
    approvalBoundary: "User sees warning and can dismiss or report.",
    failureModes: ["False positives on legitimate long-distance relationships"],
    fallbackBehavior: "Show static fraud awareness tips.",
    acceptanceCriteria: [
      "Never blocks messaging",
      "Warning includes reporting instructions",
      "False positive rate < 5%",
    ],
    status: "demo_safe",
  },
  {
    slug: "moderation-summary",
    title: "Moderation Summary",
    shortTitle: "סיכום מודרציה",
    category: "moderation",
    description: "Generates a draft summary and suggested action for a moderation case.",
    primarySurface: "Moderator Case Detail",
    availableSurfaces: ["Moderator Case Detail"],
    trigger: "Moderator clicks 'Generate AI Summary' on a case",
    userIntentServed: "Reduce cognitive load for moderators reviewing reports",
    requiredInputs: ["reportId"],
    optionalInputs: [],
    outputContract: { summary: "string", suggestedAction: "string", confidence: "low|medium|high", caveat: "string" },
    privacyNote: "Report content sent to LLM. Moderator-only access. Not shown to users.",
    safetyLevel: "critical",
    consentRequired: false,
    roleAvailability: ["moderator", "admin"],
    toolPolicy: "DRAFT ONLY. Human moderator MUST make final decision. Conservative suggestions.",
    approvalBoundary: "Moderator must explicitly select and confirm action. AI suggestion is advisory.",
    failureModes: ["Over-confident suggestions", "Hallucinated context"],
    fallbackBehavior: "Show 'Unable to generate summary — please review manually'.",
    acceptanceCriteria: [
      "Caveat always present",
      "Confidence level always included",
      "Human decision required before action",
      "Not accessible to regular users",
    ],
    status: "working",
  },
];

export default SKILL_REGISTRY;
